### ISSUE TITLE
move repository to ceph organization

### ISSUE THREAD

**Issue by ktdreyer** [alfredodeza/remoto#10]
Since this is a dependency for ceph-deploy, and ceph-deploy maintenance responsibilities are shifting to more people on the team, I think it makes sense to move this repository to the main https://github.com/ceph organization.

**Comment by ktdreyer** [comment]
cc @trhoden

**Comment by trhoden** [comment]
https://help.github.com/articles/transferring-a-repository/

I'm not sure if Alfredo has admin/owner rights in the Ceph org.  It looks like the steps would be as follows:

1. delete ceph/remoto
2. make sure alfredo has (temp) admin rights to Ceph
3. Alfredo initiate transfer to Ceph
4. Ceph admin (has to be Alfredo) accepts transfer.  Has 24-hours to complete transfer.

**Comment by ktdreyer** [comment]
Thanks for tracking that down. Looks like Alfredo's already in the "Owners" group for the Ceph org, so we're good to go on that bit at least.

**Comment by ktdreyer** [comment]
Hi @alfredodeza , just following up here to see if we could move this repo to "ceph"?

**Comment by alfredodeza** [comment]
I have added @trhoden to the administrators of this repo and a maintainer on PyPI so he can get releases/fixes out.
