### ISSUE TITLE
import_module doesnt return anything

### ISSUE THREAD

**Issue by junkmechanic** [alfredodeza/remoto#13]
Hi,
Firstly, thanks for your work on this library.

The method `import_module` should either `return self.remote_module` to be refereced by remote_foo or the documentation needs to be modified to access the attributes of the loaded module using `conn.remote_module.listdir()`, as per your example, without the need of the remote_foo.

**Comment by alfredodeza** [comment]
This is a disparity between the docs and the code. Currently this would work:

    >>> import foo
    >>> conn = Connection('hostname')
    >>> conn.import_module(foo)
    >>> conn.remote_module.listdir('.')
    ['.bash_logout',
     '.profile',
     '.veewee_version',
     '.lesshst',
     'python',
     '.vbox_version',
     'ceph',
     '.cache',
     '.ssh']

I believe I can make the docs version work, this shouldn't be that complicated, will update this soon. Thank you for reporting it.

**Comment by junkmechanic** [comment]
If you are pressed for time, I dont mind sending in a pull request :-)
