### ISSUE TITLE
None of the examples from the documentation work

### ISSUE THREAD

**Issue by l-mb** [alfredodeza/remoto#14]
None of the examples from the documentation / README actually work. Apparently, for all of them, there are certain additional steps missing that are not documented.

A single standalone example of how to use remoto to run a remote command, and one to run a single remote function call, would be really, really useful.

**Comment by alfredodeza** [comment]
@l-mb I apologize for the lacking documentation. This library was created to help the Ceph deployment tool (ceph-deploy) and we had to move as fast as we could making documentation linger behind.

I should get this addressed soon.

**Comment by alfredodeza** [comment]
Would you mind trying the examples now? I plan on extending the docs to provide more (and better) docs for the rest of functionality that was either not documented or poorly done so.

**Comment by alfredodeza** [comment]
I believe examples are accurate now, I assume you didn't find any more issues. Please feel free to re-open this issue if you feel otherwise.
