### ISSUE TITLE
Normalize outputs to string or, optionally, bytearray

### ISSUE THREAD

**Issue by HacKanCuBa** [alfredodeza/remoto#35]
The library returns either bytearray or string, one or the other w/o certain logic, which is quite an inconvenience.
Output should be normalized to, by default, an UTF-8 string or optionally, a bytearray, via a parameter.

*Note*: this is a derivative from [`ceph-deploy`](https://github.com/ceph/ceph-deploy/pull/462) issue [22816](http://tracker.ceph.com/issues/22816)

**Comment by alfredodeza** [comment]
Fixed with https://github.com/alfredodeza/remoto/commit/de833cd3502f9d388fa127f00ae6ca57b01db664
