### ISSUE TITLE
upstream (?) release missing fixes

### ISSUE THREAD

**Issue by noahdesu** [alfredodeza/remoto#42]
the fix https://github.com/alfredodeza/remoto/commit/9f5269600e31f5597d66068e5561fc23e68d405b is not in gh/ceph/remoto which is what i was using when i discovered that same bug. that repo doesn't have the fix. should users be using this repo for the most up-to-date version of remoto?

**Comment by ktdreyer** [comment]
IMHO we should remove https://github.com/ceph/remoto , because it is confusing.
